server:
  servlet:
    context-path: /crms
  port: 9000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_java
    username: postgres
    password: 123
  jpa:
    show-sql: true
  logging:
    level:
      root: DEBUG
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate=false: false
    table: schema_migrations #生成计划表名称，默认是 flyway_schema_history
