server:
  servlet:
    context-path: /crms
  port: 9000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_java
    username: postgres
    password: 123
  jpa:
    show-sql: true

  flyway:
    enabled: true
    url:  jdbc:postgresql://localhost:5432/my_java
    user: postgres
    password: 123
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0

